# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-31 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogRegApp', '0001_initial'),
        ('petSPAw_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_members',
            field=models.ManyToManyField(null=True, related_name='joined_pets', to='LogRegApp.User'),
        ),
    ]
